---
# Settings for preprocessing
# Training script will utilize some of these settings, so doing preprocessing with the provided scripts is recommended
preprocess:
  image_shape_high_resolution: [112, 112, 3]
  image_shape_low_resolution: [28, 28, 3]

# Settings for the network
network:
  embedding_size: 512
  num_filters: 64
  gc: 32
  num_blocks: 23
  residual_scailing: 0.1

# Settings for trainnig
train:
  batch_size: 16
  learning_rate: 2.e-3
  learning_rate_decay_steps: 1000
  beta_1: 0.9
  beta_2: 0.999
  weight_decay: 2.0e-4
  iterations: 30_000
  face_recognition_weight: 0.1
  super_resolution_weight: 0.1
  perceptual_weight: 1.e-3
  generator_weight: 5.e-2
  l1_weight: 1.e-2

  scale: 64
  angular_margin: 0.5

dataset:
  lfw_lr:
    path: "./datasets/LFW/Raw_Low_Resolution.tfrecords"

  vggface2_lr:
    train_path: "./datasets/VGGFace2/Train_Low_Resolution_5k.tfrecords"
    test_path: "./datasets/VGGFace2/Test_Low_Resolution_5k.tfrecords"
